"use client";

import { motion } from "framer-motion";
import { 
  HeartPulse, ShieldAlert, Cpu, Layers, Fingerprint, 
  HelpCircle, ChevronRight, Award
} from "lucide-react";
import Link from "next/link";

export default function AboutPage() {
  return (
    <div className="max-w-4xl mx-auto py-4 flex flex-col gap-10 text-left">
      
      {/* Title Header */}
      <div className="flex flex-col gap-2 border-b border-gray-900 pb-6">
        <span className="text-xs font-mono text-neonCyan font-bold uppercase tracking-widest">Scientific Overview</span>
        <h1 className="text-3xl font-extrabold tracking-tight mt-1 flex items-center gap-3">
          <HeartPulse className="w-8 h-8 text-neonCyan" /> Science & Methodology
        </h1>
        <p className="text-sm text-gray-400">Discover the dermatoglyphic theories, image processing steps, and neural architectures behind BioVision AI.</p>
      </div>

      {/* Critical Medical Disclaimer */}
      <div className="p-6 bg-red-950/20 border border-red-900/60 rounded-2xl flex flex-col md:flex-row gap-4 items-start text-left">
        <ShieldAlert className="w-8 h-8 text-red-400 shrink-0 mt-0.5" />
        <div className="flex flex-col gap-2">
          <h3 className="font-extrabold text-sm text-red-400 uppercase tracking-wider">Critical Medical Warning & Policy</h3>
          <p className="text-xs text-gray-400 leading-relaxed">
            BioVision AI is a research and dermatoglyphic estimation system. It is <span className="text-white font-bold">NOT</span> an approved medical diagnostic tool. Dermatoglyphic classification models output statistical correlations and should never be used as a clinical substitute for laboratory antigen testing (such as forwarding standard forward/reverse blood typing). 
          </p>
          <p className="text-xs text-gray-400 leading-relaxed">
            Do not make any clinical diagnoses, medical judgments, or transfusion setups based on the predictions generated by this software.
          </p>
        </div>
      </div>

      {/* 3 Pillars Section */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-4">
        
        {/* CV Pipeline details */}
        <div className="glass-panel p-6 rounded-2xl border border-gray-800 flex flex-col gap-4">
          <h3 className="font-bold text-lg text-white flex items-center gap-2">
            <Fingerprint className="w-5 h-5 text-neonCyan shadow-glowCyan" /> 1. OpenCV Image Enhancement
          </h3>
          <p className="text-xs text-gray-400 leading-relaxed">
            Paper-ink scans present high background noise, grain, and varying ink densities. To establish a clean classification signal, the raw image undergoes classical computer vision processing:
          </p>
          <ul className="text-xs text-gray-400 flex flex-col gap-2 mt-2">
            <li className="flex items-start gap-1.5">
              <ChevronRight className="w-4 h-4 text-neonCyan shrink-0" />
              <span><b>Bilateral Filtering:</b> Blurs background paper texture while preserving sharp ridge boundaries.</span>
            </li>
            <li className="flex items-start gap-1.5">
              <ChevronRight className="w-4 h-4 text-neonCyan shrink-0" />
              <span><b>CLAHE (Contrast Limiting):</b> Enhances local contrast in 8x8 pixel sub-grids, revealing faint ridge valleys without over-amplifying pixel noise.</span>
            </li>
            <li className="flex items-start gap-1.5">
              <ChevronRight className="w-4 h-4 text-neonCyan shrink-0" />
              <span><b>Adaptive Contours:</b> Binarizes print coordinates and locates the bounding box around the largest active contour to isolate and crop the print center.</span>
            </li>
          </ul>
        </div>

        {/* Quality Score Metrics */}
        <div className="glass-panel p-6 rounded-2xl border border-gray-800 flex flex-col gap-4">
          <h3 className="font-bold text-lg text-white flex items-center gap-2">
            <Award className="w-5 h-5 text-neonGreen shadow-glowGreen" /> 2. Quality Evaluation Index
          </h3>
          <p className="text-xs text-gray-400 leading-relaxed">
            Every scanned print receives an objective quality rating from 0 to 100 based on three dermatoglyphic metrics calculated in <code className="text-neonCyan bg-gray-950 px-1 py-0.5 rounded font-mono">preprocess.py</code>:
          </p>
          <ul className="text-xs text-gray-400 flex flex-col gap-3 mt-1">
            <li>
              <span className="font-bold text-white">Contrast Density (30% weight):</span>
              <p className="mt-0.5 text-gray-400 leading-relaxed">Measures global standard deviation of enhanced grayscale pixels. Perfect contrast is evaluated relative to an optimal deviation threshold of 65.0.</p>
            </li>
            <li>
              <span className="font-bold text-white">Ridge Clarity (40% weight):</span>
              <p className="mt-0.5 text-gray-400 leading-relaxed">Applies Sobel X/Y filters to calculate gradient magnitudes along ridge outlines. Higher averages mean sharper, un-smudged prints.</p>
            </li>
            <li>
              <span className="font-bold text-white">Ridge-Valley Ratio (30% weight):</span>
              <p className="mt-0.5 text-gray-400 leading-relaxed">Checks density of binarized print pixels. Ideal prints have a 45% black-to-white ratio; deviance from this ideal reduces this sub-score.</p>
            </li>
          </ul>
        </div>

        {/* Pattern Topology details */}
        <div className="glass-panel p-6 rounded-2xl border border-gray-800 flex flex-col gap-4">
          <h3 className="font-bold text-lg text-white flex items-center gap-2">
            <Layers className="w-5 h-5 text-cyberPurple shadow-glowCyan" /> 3. Ridge Topology Heuristic
          </h3>
          <p className="text-xs text-gray-400 leading-relaxed">
            Fingerprint configurations represent Loops, Whorls, or Arches. The app calculates gradients and orientation fields of the central core block to estimate this classification:
          </p>
          <ul className="text-xs text-gray-400 flex flex-col gap-2 mt-2">
            <li className="flex items-start gap-1.5">
              <ChevronRight className="w-4 h-4 text-cyberPurple shrink-0" />
              <span><b>Arch (Entropy &lt; 2.3):</b> Ridges flow uniformly horizontally with minimal angle variations.</span>
            </li>
            <li className="flex items-start gap-1.5">
              <ChevronRight className="w-4 h-4 text-cyberPurple shrink-0" />
              <span><b>Loop (Entropy 2.3 - 3.1):</b> Recurving loops yield distinct directional peak patterns.</span>
            </li>
            <li className="flex items-start gap-1.5">
              <ChevronRight className="w-4 h-4 text-cyberPurple shrink-0" />
              <span><b>Whorl (Entropy &gt; 3.1):</b> Circular ridge paths yield high angular variance, distributing directions evenly across all bins.</span>
            </li>
          </ul>
        </div>

        {/* Neural Classifier details */}
        <div className="glass-panel p-6 rounded-2xl border border-gray-800 flex flex-col gap-4">
          <h3 className="font-bold text-lg text-white flex items-center gap-2">
            <Cpu className="w-5 h-5 text-neonCyan shadow-glowCyan" /> 4. PyTorch & Grad-CAM Neural Net
          </h3>
          <p className="text-xs text-gray-400 leading-relaxed">
            Once preprocessed, the 224x224 RGB image is passed to a fine-tuned EfficientNet-B0 network:
          </p>
          <ul className="text-xs text-gray-400 flex flex-col gap-2 mt-2">
            <li className="flex items-start gap-1.5">
              <ChevronRight className="w-4 h-4 text-neonCyan shrink-0" />
              <span><b>Convolutional Core:</b> Employs pre-trained MBConv blocks to classify features into one of 8 blood groups.</span>
            </li>
            <li className="flex items-start gap-1.5">
              <ChevronRight className="w-4 h-4 text-neonCyan shrink-0" />
              <span><b>Explainability:</b> Backpropagates class gradients to the final convolutional feature layer (<code className="text-neonCyan bg-gray-950 px-1 py-0.5 rounded font-mono">features.8</code>).</span>
            </li>
            <li className="flex items-start gap-1.5">
              <ChevronRight className="w-4 h-4 text-neonCyan shrink-0" />
              <span><b>Visual Verification:</b> Resizes activation maps to overlay red-to-blue JET heatmaps, showing users which ridge details drove the estimation.</span>
            </li>
          </ul>
        </div>

      </div>

      {/* Quick Action CTA */}
      <div className="glass-panel p-8 rounded-2xl border border-gray-800 flex flex-col md:flex-row justify-between items-center gap-6">
        <div className="flex flex-col gap-2">
          <h3 className="font-bold text-xl text-white">Explore Neural Diagnostic Classification</h3>
          <p className="text-xs text-gray-400">Perform a diagnostic fingerprint scan or view model training calibration logs.</p>
        </div>
        <div className="flex gap-3 shrink-0">
          <Link href="/upload" className="px-5 py-3 rounded-lg text-xs font-bold uppercase tracking-wider text-gray-900 bg-gradient-to-r from-neonCyan to-neonGreen hover:brightness-110 shadow-glowCyan transition-all">
            Scan Print
          </Link>
        </div>
      </div>

    </div>
  );
}
